#+TITLE: org-mode-connection

This package allows to read, write and sync emacs's org-mode files.

It was developed as foundation for [[https://github.com/bnankiewicz/organic][organic]] - mobile org-mode client written in React Native.

It is designed to work both in mobile and server/desktop environments.

* Installation

#+BEGIN_SRC sh
yarn add realm promisify-node org-mode-connection
#+END_SRC

* Configuration

** with Node.js

#+name: setup
 #+BEGIN_SRC js :results output
var OrgApi = require('org-mode-connection').OrgApi
const realm = require('realm')
const promisify = require("promisify-node");
const fsInterface = promisify("fs")

// Configure
OrgApi.configureFileAccess(fsInterface);
OrgApi.configureDb(realm);
OrgApi.connectDb();
 #+END_SRC


** with React Native
#+BEGIN_SRC javascript
import OrgApi from 'org-mode-connection';
import RNFS from 'react-native-fs';
import Realm from 'realm';

// Configure
OrgApi.configureFileAccess(RNFS);
OrgApi.configureDb(Realm);
OrgApi.connectDb();
#+END_SRC

* Usage
#+BEGIN_SRC js :results output :noweb yes
const query =  async() => {
    await OrgApi.clearDb()
    await OrgApi.addFile('/home/keenan/Chaos/js.org')
    await OrgApi.syncDb()
    const res = await OrgApi.getAllFilesAsPlainObject()
    console.log(res)
}
query()
#+END_SRC
* Api
** addFile(/title/)
Creates empty file in database.

=Arguments=:
- *title*: string - New file title

=Results=:

Promise<void>

** addNodes(/nodes/, /insertPosition/, /externalChange/, /returnAddedNodes/)
Add nodes to the tree of nodes

=Arguments=:
- *nodes*: [[#PlainOrgNode][PlainOrgNode]][]
- *insertPosition*: [[#InsertPosition][InsertPosition]]
- *externalChange*: boolean
- *returnAddedNodes*: boolean

=Results=:

Promise<[[#PlainOrgNode][PlainOrgNode]][]>

** clearDb()
Clears Database.

=Results=:

Promise<void>

** configureDb(/realm/)
Configure database.

=Arguments=:
- *realm*: [[#Realm][Realm]] - Realm object

=Results=:

void

** configureFileAccess(/fsIterface/)
=Arguments=:
- *fsIterface*: [[#FsInterface][FsInterface]] - Promisified file access interface

=Results=:

void

** connectDb()
Connect database

=Results=:

Promise<void>

** createFileFromString(/name/, /lines/)
Create file from array of strings.

=Arguments=:
- *name*: string - The name of new file
- *lines*: string[] - List of string raw lines

=Results=:

Promise<void>

** deleteFileById(/fileId/)
Delete file from database.

=Arguments=:
- *fileId*: string - File id

=Results=:

Promise<void>

** deleteNodeById(/nodeId/)
Deletes node.

=Arguments=:
- *nodeId*: string

=Results=:

Promise<void>

** getAgendaAsPlainObject(/timeRange/, /defaultWarningPeriod/)
Returns agenda as plain object

=Arguments=:
- *timeRange*: [[#TimeRange][TimeRange]]
- *defaultWarningPeriod*: number

=Results=:

Promise<[[#PlainAgenda][PlainAgenda]]>

** getAllFilesAsPlainObject()
Returns all OrgFiles as plain objects

=Results=:

[[#PlainOrgFile][PlainOrgFile]][]

** getAncestorsAsPlainObject(/nodeId/)
Returns all ancestors of node.

=Arguments=:
- *nodeId*: string

=Results=:

Promise<[[#PlainOrgNode][PlainOrgNode]][]>

** getExternallyChangedFiles()
Returns ids of externally changed files

=Results=:

Promise<[[#ExternalFileChange][ExternalFileChange]][]>

** getFileAsPlainObject(/id/)
Returns file and its nodes data as plain object.

=Arguments=:
- *id*: string - File id

=Results=:

Promise<[[#PlainOrgFile][PlainOrgFile]]>

** getObjects(/model/, /filter/)
Return raw RealmResults object

=Arguments=:
- *model*: undefined - Realm model
- *filter*: string - Realm filter string

=Results=:

Promise<[[#RealmResults][RealmResults]]>

** getOrCreateNodeByHeadline(/targedNode/)
Gets node by headline. If node doasnt exists it is created.

=Arguments=:
- *targedNode*: { fileId: string, headline: string }

=Results=:

Promise<[[#PlainOrgNode][PlainOrgNode]]>

** getRelatedNodes(/nodeId/)
Returns ancestors and descendants

=Arguments=:
- *nodeId*: string

=Results=:

Promise<[[#PlainOrgNode][PlainOrgNode]][]>

** getTagsAsPlainObject()
Returns list of all tags

=Results=:

Promise<string[]>

** getTocs()
Returns all files with their child nodes

=Results=:

Promise<[[#Tocs][Tocs]]>

** importFile(/filepath/)
Imports external file

=Arguments=:
- *filepath*: string

=Results=:

Promise<void>

** search(/searchQuery/)
Search

=Arguments=:
- *searchQuery*: [[#SearchQuery][SearchQuery]]

=Results=:

Promise<any>

** syncDb()
Sync all files

=Results=:

Promise<any>

** syncFile(/id/)
Syncs file

=Arguments=:
- *id*: any - file id

=Results=:

Promise<any>

** updateFile(/id/, /changes/)
Merges prop to file object

=Arguments=:
- *id*: string - File id
- *changes*: Object - New file props to merge

=Results=:

Promise<any>

** updateNodeById(/id/, /changes/)
Merges props to node object

=Arguments=:
- *id*: string - Node id
- *changes*: Object - New node props to merge

=Results=:

Promise<any>
* Types
** PlainOrgNode
:PROPERTIES:
:CUSTOM_ID: PlainOrgNode
:END:
** PlainOrgFile
:PROPERTIES:
:CUSTOM_ID: PlainOrgFile
:END:
** InsertPosition
:PROPERTIES:
:CUSTOM_ID: InsertPosition
:END:
** Realm
:PROPERTIES:
:CUSTOM_ID: Realm
:END:
** FsInterface
:PROPERTIES:
:CUSTOM_ID: FsInterface
:END:
** PlainAgenda
:PROPERTIES:
:CUSTOM_ID: PlainAgenda
:END:
** TimeRange
:PROPERTIES:
:CUSTOM_ID: TimeRange
:END:
** ExternalFileChange
:PROPERTIES:
:CUSTOM_ID: ExternalFileChange
:END:
** Tocs
:PROPERTIES:
:CUSTOM_ID: Tocs
:END:
** SearchQuery
:PROPERTIES:
:CUSTOM_ID: SearchQuery
:END:
* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
